services:
  minio:
    image: wlcamargo/minio
    container_name: minio
    networks:
      - tcc
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=chapolin
      - MINIO_ROOT_PASSWORD=mudar@123

networks:
  tcc:
    external: true
volumes:
  minio-data:
