site_name: MkDocs Docker

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Black mode

nav:
  - Início: index.md
  - Pipeline ETL: pipeline.md
  - Airflow: airflow.md
  - Trino: trino.md
  - Superset: superset.md
  - Conclusão: conclusao.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

